### ISSUE TITLE
Use Jackrabbit FileVault API instead of deprecated com.day.jcr.vault package

### ISSUE THREAD

**Issue by kwin** [Netcentric/vault-upgrade-hook#1]
Similar to https://github.com/Netcentric/accesscontroltool/issues/106, only Jackrabbit FileVault API should be used, which is supported since AEM 6.0.

**Comment by cwoeltge** [comment]
I've made the change before I read my own comment in Readme. Unfortunately AEM6.0 doesn't execute Jackrabbit hooks. It only works with AEM6.1+
I haven't checked, if AEM6.0 SP3 would work though.

**Comment by kwin** [comment]
At least with AEM 6.0 SP3 the according bundle is installed.

**Comment by kwin** [comment]
Indeed AEM 6.0 (namely com.day.jcr.vault 2.5.6) does not support that. The used `com.day.jcr.vault.packaging.impl.JrVltInstallHookProcessor$Hook#loadMainClass(...)` only supports the old interface `com.day.jcr.vault.packaging.InstallHook` but not yet `org.apache.jackrabbit.vault.packaging.InstallHook`. But since AEM 6.0 SP3 and AEM 6.1 (namely com.day.jcr.vault 2.5.10) the `JrVltInstallHookProcessor` considers both interfaces. Both AEM 6.0 SP1 and SP2 didn't update the `com.day.jcr.vault` bundle, so the old interface is not supported with those, therefore changing to the new API would require us to increase the minimum system requirement to AEM 6 SP3 and above.
