### ISSUE TITLE
Service references are never released

### ISSUE THREAD

**Issue by kwin** [Netcentric/vault-upgrade-hook#17]
All services being retrieved through https://github.com/Netcentric/vault-upgrade-hook/blob/master/vault-upgrade-hook/src/main/java/biz/netcentric/vlt/upgrade/util/Util.java#L34 are never properly released. Not using [`BundleContext.ungetService(ServiceReference)`](https://osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleContext.html#ungetService(org.osgi.framework.ServiceReference)) leads to classloader leaks.

**Comment by andreas-haller** [comment]
True, fixed it with https://github.com/Netcentric/vault-upgrade-hook/pull/8/commits/7021314f65bc6993647ecf572da70bcaa4b462af

**Comment by kwin** [comment]
Thanks, but I would suggest using try with resources and remove the close method on the OSGiUtil.

**Comment by andreas-haller** [comment]
This would mean to upgrade to Java8, I'd like to keep Java7 compatibility for now.

**Comment by kwin** [comment]
[try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) has been introduced with Java7.

**Comment by andreas-haller** [comment]
Oh, true. Changed it.

**Comment by andreas-haller** [comment]
Fixed in 1.0.0
