### ISSUE TITLE
Get rid of Sling API

### ISSUE THREAD

**Issue by kwin** [Netcentric/vault-upgrade-hook#18]
Since hooks are a concept of Jackrabbit Filevault (and therefore bound to a JCR) only JCR API should be used but not Sling Resource API.

**Comment by andreas-haller** [comment]
Yes, noticed this too and already fixed it in https://github.com/Netcentric/vault-upgrade-hook/pull/8 the OSGi and Sling dependencies are optional and needed only for the handlers.

For https://github.com/Netcentric/vault-upgrade-hook/issues/15 I am already implementing a handler which does not need those dependencies. Will open a PR soon, after the above is merged.

**Comment by kwin** [comment]
Sling API is only used in the Pipes handler and the script handler, so I think we can close this.
