### ISSUE TITLE
Sling Pipes should get a dedicated handler

### ISSUE THREAD

**Issue by cwoeltge** [Netcentric/vault-upgrade-hook#3]
At the moment the integration of Sling Pipes is rather basic. Instead of using a Groovy script to call Sling Pipes we should use a direct Upgrade Handler. 

The missing point is here the first official release as dependency. @npeltier any timeline on that?

**Comment by npeltier** [comment]
@cwoeltge this should get in pretty soon, you can follow that up here http://markmail.org/search/?q=apache+sling+pipes+release#query:apache%20sling%20pipes%20release+page:1+mid:xkp5klw5vguekae3+state:results

**Comment by cpilsworth** [comment]
I'm preparing a PR for this change.  

Would you accept a couple of minor changes in behaviour?:

- Before loading there will be a **check to see a provider it is available** (i.e. loadClass(...))
- If the **handler is not available**, it will be logged, but the **handler will not execute**
- If there is no handler specified, **groovy will continue to be default**, if available
- If there is a **unrecognised handler** specified, it will be logged, but **groovy will not be used**.

This means that for the sample package, things will generally work the same.  If the user has sling pipes OR groovy, but upgrade hook will execute without throwing exceptions, but log any failed hooks.

**Comment by cwoeltge** [comment]
In general yes. I would not log but fail if a handler is configured but not present.

**Comment by cpilsworth** [comment]
OK, sounds like the right thing to do.

It does however mean for the sample package a user would need both Groovy Console & Sling Pipes installed. 
 
Perhaps splitting the sample package into two might help here.  User can choose which package to upload/install based upon whether they are Groovy or Sling Pipes fan.

**Comment by andreas-haller** [comment]
as far as I can see this is already done, right? should we close this issue?
