### ISSUE TITLE
include a backup pipe 

### ISSUE THREAD

**Issue by npeltier** [Netcentric/vault-upgrade-hook#36]
now there is a package pipe (https://sling.apache.org/documentation/bundles/sling-pipes/writers.html), would be nice to embed one that is executed before any of the configured pipes, on a configured set of paths, to backup content before any execution.

**Comment by andreas-haller** [comment]
nice idea, actually that would be already possible with just executing the pipe on the `PREPARE` phase or do you have a different behaviour in mind?

**Comment by npeltier** [comment]
@nc-andreashaller yes we could do this that way. The only thing is to have an easy way to configure the paths you want to backup

**Comment by cwoeltge** [comment]
With `PREPARE` and the actual order based on names would be all you need. And you can add your path there. What's the actual change you'd suggest?

**Comment by npeltier** [comment]
yeah, right, saw https://github.com/Netcentric/vault-upgrade-hook/blob/develop/samples/sling-pipes-package/src/main/upgrader/test-sling-pipes/prepare_pipe/conf/%24/.content.xml that could be a backup pipe (e.g. `csv | pkg`). Was thinking about something more embedded in the hook, but that is probably better for the hook to keep it simple and flexible
