### ISSUE TITLE
Multiple UpgradeInfo instances are not sorted as expected

### ISSUE THREAD

**Issue by Amoratinos** [Netcentric/vault-upgrade-hook#40]
While inspecting the code to use it in a project I realized that there's a little typo when multiple UpgradeInfo instances are sorted by name
https://github.com/Netcentric/vault-upgrade-hook/blob/ff039c4fab02fab9f3deb7c2d3049664298e0163/vault-upgrade-hook/src/main/java/biz/netcentric/vlt/upgrade/UpgradeProcessor.java#L175

**Comment by andreas-haller** [comment]
Thanks for the PR! I release released version 1.0.3 containing the fix.
