### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by ikritiuk** [Netcentric/vault-upgrade-hook#42]
There is an outdated step in the documentation and it's not possible to do it step-by-step:
'create a directory (like samples/groovy-package/src/main/upgrader/test-groovy)' - there is no this directory in last version(after commit https://github.com/Netcentric/vault-upgrade-hook/commit/1598f64be0055f981f748bc312cc914789385496#diff-4c6407fd0fb6690ab6d5aefc07b894be).

**Comment by andreas-haller** [comment]
Thanks for pointing it out. I update the paragraph.
