### ISSUE TITLE
Vault Upgrade Hook does not work with GroovyConsole 15

### ISSUE THREAD

**Issue by andreas-haller** [Netcentric/vault-upgrade-hook#55]
Due to an incompatible update of one of the classes in the GroovyConsole the execution of the upgrade hook fails with 

`java.lang.IncompatibleClassChangeError: Found interface com.icfolson.aem.groovy.console.response.RunScriptResponse, but class was expected`

**Comment by andreas-haller** [comment]
done with https://github.com/Netcentric/vault-upgrade-hook/pull/56

**Comment by pun-ky** [comment]
thank you very much @nc-andreashaller, however in the meantime Groovy Console 16.0.0 has been released. 
most probably it will be compatible but that need to be confirmed

**Comment by andreas-haller** [comment]
indeed, I think there is no official content package for installation yet, as soon as it is out I'll run our integration tests with it to see compatibility.

**Comment by pun-ky** [comment]
I confirm that it is working also with 16.x properly. 

Once again, thank you very much for your help. Have a nice day! ;)
