### ISSUE TITLE
Support for (yet another ;)) Groovyconsole

### ISSUE THREAD

**Issue by royteeuwen** [Netcentric/vault-upgrade-hook#61]
Superseding the https://github.com/Netcentric/vault-upgrade-hook/issues/60 ticket. Seeing as the groovyconsole doesn't seem to be maintained anymore by CIF / icfnext, we have decided to fork it and create a new release ourselves.

This ticket is to get the new groovyconsole merged:

https://github.com/orbinson/aem-groovy-console

**Comment by royteeuwen** [comment]
@kwin  any chance you can have a look at this? AECU and the Groovy console have already been released, but now we have conflicts in our own projects because we also use vault-upgrade-hook, which still uses the old groovy console

**Comment by andreas-haller** [comment]
Hi Roy,
sorry for the late response. Looking into this asap and will potentially create a new release for the changes.

**Comment by royteeuwen** [comment]
Thanks @nc-andreashaller !
We are also checking to upgrade to the latest groovy version: https://github.com/orbinson/aem-groovy-console/issues/7

We will release this with a new mayor version, so ideally there could be two releases for the vault upgrade hook, one for the current that still supports groovy 2.x and one for the 4.x

**Comment by royteeuwen** [comment]
@nc-andreashaller aem groovy console 19.0.1 is now released, which works wirh Groovy 4.0.9+ 👌🏼

**Comment by andreas-haller** [comment]
Released [version 3.0.0](https://central.sonatype.com/artifact/biz.netcentric.vlt.upgrade/vault-upgrade-hook/3.0.0) today and tested with the 18 and 19 version of the console.
